### PR TITLE
Fix Authserver and Realmserver startup

### PR DESCRIPTION
**Pull request by Ness199X**
- Fix Authserver rejecting valid initialization packets due to expecting them to be one byte larger
- Fix the 'Realms' table not having a Population column

### CODE REVIEW

**Comment by Fabi** [comment]
Did you get a 255 byte 'Connection' packet? Maybe I have to take a look for the real min. size :D

**Comment by Ness199X** [comment]
Seems to always be 255 whenever I run the client.

**Comment by Fabi** [comment]
Could you post the packet? so I can see what it contains?

**Comment by Ness199X** [comment]
You seem to have disabled packetlogging in Authserv and I couldn't figure out how to re-enable it, so heres the packet data as a hex string:
`50-4F-53-54-20-2F-53-74-73-2F-43-6F-6E-6E-65-63-74-20-53-54-53-2F-31-2E-30-0D-0A-6C-3A-32-31-39-0D-0A-0D-0A-3C-43-6F-6E-6E-65-63-74-3E-0A-3C-43-6F-6E-6E-54-79-70-65-3E-34-30-30-3C-2F-43-6F-6E-6E-54-79-70-65-3E-0A-3C-41-64-64-72-65-73-73-3E-31-30-2E-30-2E-30-2E-31-34-3C-2F-41-64-64-72-65-73-73-3E-0A-3C-50-72-6F-64-75-63-74-54-79-70-65-3E-30-3C-2F-50-72-6F-64-75-63-74-54-79-70-65-3E-0A-3C-41-70-70-49-6E-64-65-78-3E-31-3C-2F-41-70-70-49-6E-64-65-78-3E-0A-3C-45-70-6F-63-68-3E-34-36-32-33-36-32-38-34-30-3C-2F-45-70-6F-63-68-3E-0A-3C-50-72-6F-67-72-61-6D-3E-39-30-32-3C-2F-50-72-6F-67-72-61-6D-3E-0A-3C-42-75-69-6C-64-3E-31-30-30-31-3C-2F-42-75-69-6C-64-3E-0A-3C-50-72-6F-63-65-73-73-3E-36-38-39-32-3C-2F-50-72-6F-63-65-73-73-3E-0A-3C-2F-43-6F-6E-6E-65-63-74-3E-0A`

**Comment by Ness199X** [comment]
I must admit, I am interested which build the server is supposed to support, you just pushed an update to build 9234, but my updated client is build 9024

**Comment by Ness199X** [comment]
I just realized you are targeting the F2P client, not the Live client, which I did this testing on

**Comment by Fabi** [comment]
I think it should be set to min 250 bytes.

**Comment by Ness199X** [comment]
Done

**Comment by Fabi** [comment]
There is an irc channel at rizon. #Multi-Emu

**Pull request merged**
